Adding CI tests
alleyinteractive/Alley-Coding-Standards pull request #40
Opened 2024-07-17 17:45 UTC by srtfisher

- **Ignoring DS_Store**
- **Adding CI tests**

2024-07-17 22:17 UTC, renatonascalves requested changes

2024-07-17 22:17 UTC, renatonascalves commented on Alley-Interactive/ruleset.xml
> +  <!-- Allow PSR-4 file format for test files -->
Looks misaligned.

2024-07-18 13:56 UTC, srtfisher commented on Alley-Interactive/ruleset.xml
> +  <!-- Allow PSR-4 file format for test files -->
Good eye

2024-07-18 13:57 UTC, renatonascalves approved these changes
🌵

2024-07-18 14:05 UTC, merged